name: Build Skia Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NDK_VERSION: r27c

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git cmake ninja-build wget unzip curl

      - name: Set up Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          add-to-path: true

      - name: Set environment variables
        run: echo "ANDROID_NDK_PATH=${ANDROID_NDK_HOME}" >> $GITHUB_ENV

      - name: Setup depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH

      - name: Checkout Skia
        run: |
          git clone https://github.com/google/skia.git skia
          cd skia
          git checkout main

      - name: Fetch Skia dependencies
        run: |
          cd skia
          python3 tools/git-sync-deps

      - name: Build Skia for Android (arm64)
        run: |
          cd skia
          mkdir -p out/android-arm64
          python3 tools/gn.py gen out/android-arm64 \
            --args='
            target_os="android"
            target_cpu="arm64"
            is_official_build=true
            skia_use_system_freetype2=false
            skia_use_gl=true
            skia_use_vulkan=false
            skia_use_metal=false
            skia_use_fontconfig=false
            ' 
          ninja -C out/android-arm64

      - name: Upload built .so and headers
        uses: actions/upload-artifact@v4
        with:
          name: skia-android-artifact
          path: |
            skia/out/android-arm64/libskia.so
            skia/include/**/*

