name: Build Skia Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      ANDROID_HOME: $HOME/Android/Sdk

    steps:
      - name: Checkout Skia repo
        uses: actions/checkout@v4
        with:
          repository: google/skia
          path: skia

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git cmake ninja-build wget unzip curl openjdk-11-jdk

      - name: Fetch Skia helper tool
        run: |
          cd skia
          ./bin/fetch-sk

      - name: Download Android NDK via sk tool
        run: |
          cd skia
          ./bin/sk asset download android_ndk_linux $HOME/ndk
          echo "ANDROID_NDK_HOME=$HOME/ndk" >> $GITHUB_ENV

      - name: Build Skia for multiple Android ABIs
        run: |
          cd skia
          ABIS=("arm" "arm64" "x86" "x64")
          for ABI in "${ABIS[@]}"; do
            mkdir -p out/android-$ABI
            python3 tools/gn.py gen out/android-$ABI --args="ndk=\"$HOME/ndk\" target_cpu=\"$ABI\" is_official_build=true skia_use_gl=true skia_use_vulkan=false skia_use_metal=false skia_use_system_freetype2=false skia_use_fontconfig=false"
            ninja -C out/android-$ABI
          done

      - name: Upload built .so files and headers
        uses: actions/upload-artifact@v4
        with:
          name: skia-android-artifact
          path: |
            skia/out/android-*/libskia.so
            skia/include/**/*

